"use client";

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import {
	type AppLolChampionCardCustomEvent,
	type AppLolChampionFilterCustomEvent,
	type AppLolLobbyListCustomEvent,
	type AppTimerCustomEvent,
	type ChampionRole,
	type ComposeEventDetail,
	type LobbyJoinEvent,
	type SsvComposeCustomEvent,
} from "@app/stencil-playground";
import type { Components } from "@app/stencil-playground/dist/components";
import { AppComposeDemo as AppComposeDemoElement } from "@app/stencil-playground/dist/components/app-compose-demo.js";
import { AppCounter as AppCounterElement } from "@app/stencil-playground/dist/components/app-counter.js";
import { AppCtxCounterGroup as AppCtxCounterGroupElement } from "@app/stencil-playground/dist/components/app-ctx-counter-group.js";
import { AppCtxCounter as AppCtxCounterElement } from "@app/stencil-playground/dist/components/app-ctx-counter.js";
import { AppEffectDemo as AppEffectDemoElement } from "@app/stencil-playground/dist/components/app-effect-demo.js";
import { AppIntersectionObserver as AppIntersectionObserverElement } from "@app/stencil-playground/dist/components/app-intersection-observer.js";
import { AppLifecycleDemo as AppLifecycleDemoElement } from "@app/stencil-playground/dist/components/app-lifecycle-demo.js";
import { AppLolChampionCard as AppLolChampionCardElement } from "@app/stencil-playground/dist/components/app-lol-champion-card.js";
import { AppLolChampionFilter as AppLolChampionFilterElement } from "@app/stencil-playground/dist/components/app-lol-champion-filter.js";
import { AppLolChampionPool as AppLolChampionPoolElement } from "@app/stencil-playground/dist/components/app-lol-champion-pool.js";
import { AppLolDraftArea as AppLolDraftAreaElement } from "@app/stencil-playground/dist/components/app-lol-draft-area.js";
import { AppLolDraftHeroCard as AppLolDraftHeroCardElement } from "@app/stencil-playground/dist/components/app-lol-draft-hero-card.js";
import { AppLolDraftInfo as AppLolDraftInfoElement } from "@app/stencil-playground/dist/components/app-lol-draft-info.js";
import { AppLolDraftLayout as AppLolDraftLayoutElement } from "@app/stencil-playground/dist/components/app-lol-draft-layout.js";
import { AppLolDraftLobbyHost as AppLolDraftLobbyHostElement } from "@app/stencil-playground/dist/components/app-lol-draft-lobby-host.js";
import { AppLolDraftSlot as AppLolDraftSlotElement } from "@app/stencil-playground/dist/components/app-lol-draft-slot.js";
import { AppLolLobbyList as AppLolLobbyListElement } from "@app/stencil-playground/dist/components/app-lol-lobby-list.js";
import { AppLolNotification as AppLolNotificationElement } from "@app/stencil-playground/dist/components/app-lol-notification.js";
import { AppLolTeamSection as AppLolTeamSectionElement } from "@app/stencil-playground/dist/components/app-lol-team-section.js";
import { AppMouseHost as AppMouseHostElement } from "@app/stencil-playground/dist/components/app-mouse-host.js";
import { AppMutationObserver as AppMutationObserverElement } from "@app/stencil-playground/dist/components/app-mutation-observer.js";
import { AppResizeObserver as AppResizeObserverElement } from "@app/stencil-playground/dist/components/app-resize-observer.js";
import { AppSignalsComputedPrevious as AppSignalsComputedPreviousElement } from "@app/stencil-playground/dist/components/app-signals-computed-previous.js";
import { AppSignalsCounter as AppSignalsCounterElement } from "@app/stencil-playground/dist/components/app-signals-counter.js";
import { AppSignalsDerivedAsync as AppSignalsDerivedAsyncElement } from "@app/stencil-playground/dist/components/app-signals-derived-async.js";
import { AppSignalsMouseEvent as AppSignalsMouseEventElement } from "@app/stencil-playground/dist/components/app-signals-mouse-event.js";
import { AppSignalsObserverSignals as AppSignalsObserverSignalsElement } from "@app/stencil-playground/dist/components/app-signals-observer-signals.js";
import { AppSignalsTodo as AppSignalsTodoElement } from "@app/stencil-playground/dist/components/app-signals-todo.js";
import { AppStartupContextInspector as AppStartupContextInspectorElement } from "@app/stencil-playground/dist/components/app-startup-context-inspector.js";
import { AppStartupContextProvider as AppStartupContextProviderElement } from "@app/stencil-playground/dist/components/app-startup-context-provider.js";
import { AppTanCounter as AppTanCounterElement } from "@app/stencil-playground/dist/components/app-tan-counter.js";
import { AppTanTodo as AppTanTodoElement } from "@app/stencil-playground/dist/components/app-tan-todo.js";
import { AppTimerCounter as AppTimerCounterElement } from "@app/stencil-playground/dist/components/app-timer-counter.js";
import { AppTimerHost as AppTimerHostElement } from "@app/stencil-playground/dist/components/app-timer-host.js";
import { AppTimer as AppTimerElement } from "@app/stencil-playground/dist/components/app-timer.js";
import { AppTodo as AppTodoElement } from "@app/stencil-playground/dist/components/app-todo.js";
import { AppTransferState as AppTransferStateElement } from "@app/stencil-playground/dist/components/app-transfer-state.js";
import { AppTranslationProfile as AppTranslationProfileElement } from "@app/stencil-playground/dist/components/app-translation-profile.js";
import { AppTranslationShell as AppTranslationShellElement } from "@app/stencil-playground/dist/components/app-translation-shell.js";
import { AppTranslationsHost as AppTranslationsHostElement } from "@app/stencil-playground/dist/components/app-translations-host.js";
import { AppTsQueryHoverPrefetch as AppTsQueryHoverPrefetchElement } from "@app/stencil-playground/dist/components/app-ts-query-hover-prefetch.js";
import { AppTsQueryPostsSignals as AppTsQueryPostsSignalsElement } from "@app/stencil-playground/dist/components/app-ts-query-posts-signals.js";
import { AppTsQueryPosts as AppTsQueryPostsElement } from "@app/stencil-playground/dist/components/app-ts-query-posts.js";
import { AppTsQueryPrefetchDemo as AppTsQueryPrefetchDemoElement } from "@app/stencil-playground/dist/components/app-ts-query-prefetch-demo.js";
import { AppTsQueryPrefetchReuse as AppTsQueryPrefetchReuseElement } from "@app/stencil-playground/dist/components/app-ts-query-prefetch-reuse.js";
import { AppTsQueryPrefetch as AppTsQueryPrefetchElement } from "@app/stencil-playground/dist/components/app-ts-query-prefetch.js";
import { AppTsQueryUseQueriesDemo as AppTsQueryUseQueriesDemoElement } from "@app/stencil-playground/dist/components/app-ts-query-use-queries-demo.js";
import { AppTsQueryUseQueriesInline as AppTsQueryUseQueriesInlineElement } from "@app/stencil-playground/dist/components/app-ts-query-use-queries-inline.js";
import { AppTsQueryUseQueriesReuse as AppTsQueryUseQueriesReuseElement } from "@app/stencil-playground/dist/components/app-ts-query-use-queries-reuse.js";
import { AppTsQueryUseQueriesSignalsCombine as AppTsQueryUseQueriesSignalsCombineElement } from "@app/stencil-playground/dist/components/app-ts-query-use-queries-signals-combine.js";
import { AppTsQueryUseQueriesSignals as AppTsQueryUseQueriesSignalsElement } from "@app/stencil-playground/dist/components/app-ts-query-use-queries-signals.js";
import { SsvCompose as SsvComposeElement } from "@app/stencil-playground/dist/components/ssv-compose.js";
// @ts-ignore - ignore potential type issues as the project is importing itself
import * as clientComponents from "@app/stencil-playground/react-client";
import type { EventName, StencilReactComponent } from "@stencil/react-output-target/runtime";
import { createComponent, type HydrateModule, type SerializeShadowRootOptions } from "@stencil/react-output-target/ssr";

export const serializeShadowRoot: SerializeShadowRootOptions = { default: "declarative-shadow-dom" };

export type AppComposeDemoEvents = NonNullable<unknown>;

export const AppComposeDemo: StencilReactComponent<
	AppComposeDemoElement,
	AppComposeDemoEvents,
	Components.AppComposeDemo
> = /*@__PURE__*/ createComponent<AppComposeDemoElement, AppComposeDemoEvents, Components.AppComposeDemo>({
	tagName: "app-compose-demo",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppComposeDemo as StencilReactComponent<
		AppComposeDemoElement,
		AppComposeDemoEvents,
		Components.AppComposeDemo
	>,
	serializeShadowRoot,
});

export type AppCounterEvents = NonNullable<unknown>;

export const AppCounter: StencilReactComponent<AppCounterElement, AppCounterEvents, Components.AppCounter> =
	/*@__PURE__*/ createComponent<AppCounterElement, AppCounterEvents, Components.AppCounter>({
		tagName: "app-counter",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppCounter as StencilReactComponent<
			AppCounterElement,
			AppCounterEvents,
			Components.AppCounter
		>,
		serializeShadowRoot,
	});

export type AppCtxCounterEvents = NonNullable<unknown>;

export const AppCtxCounter: StencilReactComponent<AppCtxCounterElement, AppCtxCounterEvents, Components.AppCtxCounter> =
	/*@__PURE__*/ createComponent<AppCtxCounterElement, AppCtxCounterEvents, Components.AppCtxCounter>({
		tagName: "app-ctx-counter",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppCtxCounter as StencilReactComponent<
			AppCtxCounterElement,
			AppCtxCounterEvents,
			Components.AppCtxCounter
		>,
		serializeShadowRoot,
	});

export type AppCtxCounterGroupEvents = NonNullable<unknown>;

export const AppCtxCounterGroup: StencilReactComponent<
	AppCtxCounterGroupElement,
	AppCtxCounterGroupEvents,
	Components.AppCtxCounterGroup
> = /*@__PURE__*/ createComponent<AppCtxCounterGroupElement, AppCtxCounterGroupEvents, Components.AppCtxCounterGroup>({
	tagName: "app-ctx-counter-group",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppCtxCounterGroup as StencilReactComponent<
		AppCtxCounterGroupElement,
		AppCtxCounterGroupEvents,
		Components.AppCtxCounterGroup
	>,
	serializeShadowRoot,
});

export type AppEffectDemoEvents = NonNullable<unknown>;

export const AppEffectDemo: StencilReactComponent<AppEffectDemoElement, AppEffectDemoEvents, Components.AppEffectDemo> =
	/*@__PURE__*/ createComponent<AppEffectDemoElement, AppEffectDemoEvents, Components.AppEffectDemo>({
		tagName: "app-effect-demo",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppEffectDemo as StencilReactComponent<
			AppEffectDemoElement,
			AppEffectDemoEvents,
			Components.AppEffectDemo
		>,
		serializeShadowRoot,
	});

export type AppIntersectionObserverEvents = NonNullable<unknown>;

export const AppIntersectionObserver: StencilReactComponent<
	AppIntersectionObserverElement,
	AppIntersectionObserverEvents,
	Components.AppIntersectionObserver
> = /*@__PURE__*/ createComponent<
	AppIntersectionObserverElement,
	AppIntersectionObserverEvents,
	Components.AppIntersectionObserver
>({
	tagName: "app-intersection-observer",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppIntersectionObserver as StencilReactComponent<
		AppIntersectionObserverElement,
		AppIntersectionObserverEvents,
		Components.AppIntersectionObserver
	>,
	serializeShadowRoot,
});

export type AppLifecycleDemoEvents = NonNullable<unknown>;

export const AppLifecycleDemo: StencilReactComponent<
	AppLifecycleDemoElement,
	AppLifecycleDemoEvents,
	Components.AppLifecycleDemo
> = /*@__PURE__*/ createComponent<AppLifecycleDemoElement, AppLifecycleDemoEvents, Components.AppLifecycleDemo>({
	tagName: "app-lifecycle-demo",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLifecycleDemo as StencilReactComponent<
		AppLifecycleDemoElement,
		AppLifecycleDemoEvents,
		Components.AppLifecycleDemo
	>,
	serializeShadowRoot,
});

export type AppLolChampionCardEvents = { onChampionSelect: EventName<AppLolChampionCardCustomEvent<string>> };

export const AppLolChampionCard: StencilReactComponent<
	AppLolChampionCardElement,
	AppLolChampionCardEvents,
	Components.AppLolChampionCard
> = /*@__PURE__*/ createComponent<AppLolChampionCardElement, AppLolChampionCardEvents, Components.AppLolChampionCard>({
	tagName: "app-lol-champion-card",
	properties: {
		disabled: "disabled",
		status: "status",
	},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolChampionCard as StencilReactComponent<
		AppLolChampionCardElement,
		AppLolChampionCardEvents,
		Components.AppLolChampionCard
	>,
	serializeShadowRoot,
});

export type AppLolChampionFilterEvents = {
	onSearchChange: EventName<AppLolChampionFilterCustomEvent<string>>;
	onRoleToggle: EventName<AppLolChampionFilterCustomEvent<ChampionRole>>;
	onClearFilters: EventName<AppLolChampionFilterCustomEvent<void>>;
};

export const AppLolChampionFilter: StencilReactComponent<
	AppLolChampionFilterElement,
	AppLolChampionFilterEvents,
	Components.AppLolChampionFilter
> = /*@__PURE__*/ createComponent<
	AppLolChampionFilterElement,
	AppLolChampionFilterEvents,
	Components.AppLolChampionFilter
>({
	tagName: "app-lol-champion-filter",
	properties: { search: "search" },
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolChampionFilter as StencilReactComponent<
		AppLolChampionFilterElement,
		AppLolChampionFilterEvents,
		Components.AppLolChampionFilter
	>,
	serializeShadowRoot,
});

export type AppLolChampionPoolEvents = NonNullable<unknown>;

export const AppLolChampionPool: StencilReactComponent<
	AppLolChampionPoolElement,
	AppLolChampionPoolEvents,
	Components.AppLolChampionPool
> = /*@__PURE__*/ createComponent<AppLolChampionPoolElement, AppLolChampionPoolEvents, Components.AppLolChampionPool>({
	tagName: "app-lol-champion-pool",
	properties: {
		draftId: "draft-id",
		team: "team",
	},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolChampionPool as StencilReactComponent<
		AppLolChampionPoolElement,
		AppLolChampionPoolEvents,
		Components.AppLolChampionPool
	>,
	serializeShadowRoot,
});

export type AppLolDraftAreaEvents = NonNullable<unknown>;

export const AppLolDraftArea: StencilReactComponent<
	AppLolDraftAreaElement,
	AppLolDraftAreaEvents,
	Components.AppLolDraftArea
> = /*@__PURE__*/ createComponent<AppLolDraftAreaElement, AppLolDraftAreaEvents, Components.AppLolDraftArea>({
	tagName: "app-lol-draft-area",
	properties: {
		draftId: "draft-id",
		myTeam: "my-team",
	},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolDraftArea as StencilReactComponent<
		AppLolDraftAreaElement,
		AppLolDraftAreaEvents,
		Components.AppLolDraftArea
	>,
	serializeShadowRoot,
});

export type AppLolDraftHeroCardEvents = NonNullable<unknown>;

export const AppLolDraftHeroCard: StencilReactComponent<
	AppLolDraftHeroCardElement,
	AppLolDraftHeroCardEvents,
	Components.AppLolDraftHeroCard
> = /*@__PURE__*/ createComponent<
	AppLolDraftHeroCardElement,
	AppLolDraftHeroCardEvents,
	Components.AppLolDraftHeroCard
>({
	tagName: "app-lol-draft-hero-card",
	properties: { slotType: "slot-type" },
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolDraftHeroCard as StencilReactComponent<
		AppLolDraftHeroCardElement,
		AppLolDraftHeroCardEvents,
		Components.AppLolDraftHeroCard
	>,
	serializeShadowRoot,
});

export type AppLolDraftInfoEvents = NonNullable<unknown>;

export const AppLolDraftInfo: StencilReactComponent<
	AppLolDraftInfoElement,
	AppLolDraftInfoEvents,
	Components.AppLolDraftInfo
> = /*@__PURE__*/ createComponent<AppLolDraftInfoElement, AppLolDraftInfoEvents, Components.AppLolDraftInfo>({
	tagName: "app-lol-draft-info",
	properties: {
		draftId: "draft-id",
		myTeam: "my-team",
	},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolDraftInfo as StencilReactComponent<
		AppLolDraftInfoElement,
		AppLolDraftInfoEvents,
		Components.AppLolDraftInfo
	>,
	serializeShadowRoot,
});

export type AppLolDraftLayoutEvents = NonNullable<unknown>;

export const AppLolDraftLayout: StencilReactComponent<
	AppLolDraftLayoutElement,
	AppLolDraftLayoutEvents,
	Components.AppLolDraftLayout
> = /*@__PURE__*/ createComponent<AppLolDraftLayoutElement, AppLolDraftLayoutEvents, Components.AppLolDraftLayout>({
	tagName: "app-lol-draft-layout",
	properties: { sessionId: "session-id" },
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolDraftLayout as StencilReactComponent<
		AppLolDraftLayoutElement,
		AppLolDraftLayoutEvents,
		Components.AppLolDraftLayout
	>,
	serializeShadowRoot,
});

export type AppLolDraftLobbyHostEvents = NonNullable<unknown>;

export const AppLolDraftLobbyHost: StencilReactComponent<
	AppLolDraftLobbyHostElement,
	AppLolDraftLobbyHostEvents,
	Components.AppLolDraftLobbyHost
> = /*@__PURE__*/ createComponent<
	AppLolDraftLobbyHostElement,
	AppLolDraftLobbyHostEvents,
	Components.AppLolDraftLobbyHost
>({
	tagName: "app-lol-draft-lobby-host",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolDraftLobbyHost as StencilReactComponent<
		AppLolDraftLobbyHostElement,
		AppLolDraftLobbyHostEvents,
		Components.AppLolDraftLobbyHost
	>,
	serializeShadowRoot,
});

export type AppLolDraftSlotEvents = NonNullable<unknown>;

export const AppLolDraftSlot: StencilReactComponent<
	AppLolDraftSlotElement,
	AppLolDraftSlotEvents,
	Components.AppLolDraftSlot
> = /*@__PURE__*/ createComponent<AppLolDraftSlotElement, AppLolDraftSlotEvents, Components.AppLolDraftSlot>({
	tagName: "app-lol-draft-slot",
	properties: {
		slotType: "slot-type",
		status: "status",
	},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolDraftSlot as StencilReactComponent<
		AppLolDraftSlotElement,
		AppLolDraftSlotEvents,
		Components.AppLolDraftSlot
	>,
	serializeShadowRoot,
});

export type AppLolLobbyListEvents = {
	onAppCreate: EventName<AppLolLobbyListCustomEvent<LobbyJoinEvent>>;
	onAppJoin: EventName<AppLolLobbyListCustomEvent<LobbyJoinEvent>>;
};

export const AppLolLobbyList: StencilReactComponent<
	AppLolLobbyListElement,
	AppLolLobbyListEvents,
	Components.AppLolLobbyList
> = /*@__PURE__*/ createComponent<AppLolLobbyListElement, AppLolLobbyListEvents, Components.AppLolLobbyList>({
	tagName: "app-lol-lobby-list",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolLobbyList as StencilReactComponent<
		AppLolLobbyListElement,
		AppLolLobbyListEvents,
		Components.AppLolLobbyList
	>,
	serializeShadowRoot,
});

export type AppLolNotificationEvents = NonNullable<unknown>;

export const AppLolNotification: StencilReactComponent<
	AppLolNotificationElement,
	AppLolNotificationEvents,
	Components.AppLolNotification
> = /*@__PURE__*/ createComponent<AppLolNotificationElement, AppLolNotificationEvents, Components.AppLolNotification>({
	tagName: "app-lol-notification",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolNotification as StencilReactComponent<
		AppLolNotificationElement,
		AppLolNotificationEvents,
		Components.AppLolNotification
	>,
	serializeShadowRoot,
});

export type AppLolTeamSectionEvents = NonNullable<unknown>;

export const AppLolTeamSection: StencilReactComponent<
	AppLolTeamSectionElement,
	AppLolTeamSectionEvents,
	Components.AppLolTeamSection
> = /*@__PURE__*/ createComponent<AppLolTeamSectionElement, AppLolTeamSectionEvents, Components.AppLolTeamSection>({
	tagName: "app-lol-team-section",
	properties: {
		team: "team",
		isActive: "is-active",
	},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppLolTeamSection as StencilReactComponent<
		AppLolTeamSectionElement,
		AppLolTeamSectionEvents,
		Components.AppLolTeamSection
	>,
	serializeShadowRoot,
});

export type AppMouseHostEvents = NonNullable<unknown>;

export const AppMouseHost: StencilReactComponent<AppMouseHostElement, AppMouseHostEvents, Components.AppMouseHost> =
	/*@__PURE__*/ createComponent<AppMouseHostElement, AppMouseHostEvents, Components.AppMouseHost>({
		tagName: "app-mouse-host",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppMouseHost as StencilReactComponent<
			AppMouseHostElement,
			AppMouseHostEvents,
			Components.AppMouseHost
		>,
		serializeShadowRoot,
	});

export type AppMutationObserverEvents = NonNullable<unknown>;

export const AppMutationObserver: StencilReactComponent<
	AppMutationObserverElement,
	AppMutationObserverEvents,
	Components.AppMutationObserver
> = /*@__PURE__*/ createComponent<
	AppMutationObserverElement,
	AppMutationObserverEvents,
	Components.AppMutationObserver
>({
	tagName: "app-mutation-observer",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppMutationObserver as StencilReactComponent<
		AppMutationObserverElement,
		AppMutationObserverEvents,
		Components.AppMutationObserver
	>,
	serializeShadowRoot,
});

export type AppResizeObserverEvents = NonNullable<unknown>;

export const AppResizeObserver: StencilReactComponent<
	AppResizeObserverElement,
	AppResizeObserverEvents,
	Components.AppResizeObserver
> = /*@__PURE__*/ createComponent<AppResizeObserverElement, AppResizeObserverEvents, Components.AppResizeObserver>({
	tagName: "app-resize-observer",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppResizeObserver as StencilReactComponent<
		AppResizeObserverElement,
		AppResizeObserverEvents,
		Components.AppResizeObserver
	>,
	serializeShadowRoot,
});

export type AppSignalsComputedPreviousEvents = NonNullable<unknown>;

export const AppSignalsComputedPrevious: StencilReactComponent<
	AppSignalsComputedPreviousElement,
	AppSignalsComputedPreviousEvents,
	Components.AppSignalsComputedPrevious
> = /*@__PURE__*/ createComponent<
	AppSignalsComputedPreviousElement,
	AppSignalsComputedPreviousEvents,
	Components.AppSignalsComputedPrevious
>({
	tagName: "app-signals-computed-previous",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppSignalsComputedPrevious as StencilReactComponent<
		AppSignalsComputedPreviousElement,
		AppSignalsComputedPreviousEvents,
		Components.AppSignalsComputedPrevious
	>,
	serializeShadowRoot,
});

export type AppSignalsCounterEvents = NonNullable<unknown>;

export const AppSignalsCounter: StencilReactComponent<
	AppSignalsCounterElement,
	AppSignalsCounterEvents,
	Components.AppSignalsCounter
> = /*@__PURE__*/ createComponent<AppSignalsCounterElement, AppSignalsCounterEvents, Components.AppSignalsCounter>({
	tagName: "app-signals-counter",
	properties: { step: "step" },
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppSignalsCounter as StencilReactComponent<
		AppSignalsCounterElement,
		AppSignalsCounterEvents,
		Components.AppSignalsCounter
	>,
	serializeShadowRoot,
});

export type AppSignalsDerivedAsyncEvents = NonNullable<unknown>;

export const AppSignalsDerivedAsync: StencilReactComponent<
	AppSignalsDerivedAsyncElement,
	AppSignalsDerivedAsyncEvents,
	Components.AppSignalsDerivedAsync
> = /*@__PURE__*/ createComponent<
	AppSignalsDerivedAsyncElement,
	AppSignalsDerivedAsyncEvents,
	Components.AppSignalsDerivedAsync
>({
	tagName: "app-signals-derived-async",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppSignalsDerivedAsync as StencilReactComponent<
		AppSignalsDerivedAsyncElement,
		AppSignalsDerivedAsyncEvents,
		Components.AppSignalsDerivedAsync
	>,
	serializeShadowRoot,
});

export type AppSignalsMouseEventEvents = NonNullable<unknown>;

export const AppSignalsMouseEvent: StencilReactComponent<
	AppSignalsMouseEventElement,
	AppSignalsMouseEventEvents,
	Components.AppSignalsMouseEvent
> = /*@__PURE__*/ createComponent<
	AppSignalsMouseEventElement,
	AppSignalsMouseEventEvents,
	Components.AppSignalsMouseEvent
>({
	tagName: "app-signals-mouse-event",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppSignalsMouseEvent as StencilReactComponent<
		AppSignalsMouseEventElement,
		AppSignalsMouseEventEvents,
		Components.AppSignalsMouseEvent
	>,
	serializeShadowRoot,
});

export type AppSignalsObserverSignalsEvents = NonNullable<unknown>;

export const AppSignalsObserverSignals: StencilReactComponent<
	AppSignalsObserverSignalsElement,
	AppSignalsObserverSignalsEvents,
	Components.AppSignalsObserverSignals
> = /*@__PURE__*/ createComponent<
	AppSignalsObserverSignalsElement,
	AppSignalsObserverSignalsEvents,
	Components.AppSignalsObserverSignals
>({
	tagName: "app-signals-observer-signals",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppSignalsObserverSignals as StencilReactComponent<
		AppSignalsObserverSignalsElement,
		AppSignalsObserverSignalsEvents,
		Components.AppSignalsObserverSignals
	>,
	serializeShadowRoot,
});

export type AppSignalsTodoEvents = NonNullable<unknown>;

export const AppSignalsTodo: StencilReactComponent<
	AppSignalsTodoElement,
	AppSignalsTodoEvents,
	Components.AppSignalsTodo
> = /*@__PURE__*/ createComponent<AppSignalsTodoElement, AppSignalsTodoEvents, Components.AppSignalsTodo>({
	tagName: "app-signals-todo",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppSignalsTodo as StencilReactComponent<
		AppSignalsTodoElement,
		AppSignalsTodoEvents,
		Components.AppSignalsTodo
	>,
	serializeShadowRoot,
});

export type AppStartupContextInspectorEvents = NonNullable<unknown>;

export const AppStartupContextInspector: StencilReactComponent<
	AppStartupContextInspectorElement,
	AppStartupContextInspectorEvents,
	Components.AppStartupContextInspector
> = /*@__PURE__*/ createComponent<
	AppStartupContextInspectorElement,
	AppStartupContextInspectorEvents,
	Components.AppStartupContextInspector
>({
	tagName: "app-startup-context-inspector",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppStartupContextInspector as StencilReactComponent<
		AppStartupContextInspectorElement,
		AppStartupContextInspectorEvents,
		Components.AppStartupContextInspector
	>,
	serializeShadowRoot,
});

export type AppStartupContextProviderEvents = NonNullable<unknown>;

export const AppStartupContextProvider: StencilReactComponent<
	AppStartupContextProviderElement,
	AppStartupContextProviderEvents,
	Components.AppStartupContextProvider
> = /*@__PURE__*/ createComponent<
	AppStartupContextProviderElement,
	AppStartupContextProviderEvents,
	Components.AppStartupContextProvider
>({
	tagName: "app-startup-context-provider",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppStartupContextProvider as StencilReactComponent<
		AppStartupContextProviderElement,
		AppStartupContextProviderEvents,
		Components.AppStartupContextProvider
	>,
	serializeShadowRoot,
});

export type AppTanCounterEvents = NonNullable<unknown>;

export const AppTanCounter: StencilReactComponent<AppTanCounterElement, AppTanCounterEvents, Components.AppTanCounter> =
	/*@__PURE__*/ createComponent<AppTanCounterElement, AppTanCounterEvents, Components.AppTanCounter>({
		tagName: "app-tan-counter",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppTanCounter as StencilReactComponent<
			AppTanCounterElement,
			AppTanCounterEvents,
			Components.AppTanCounter
		>,
		serializeShadowRoot,
	});

export type AppTanTodoEvents = NonNullable<unknown>;

export const AppTanTodo: StencilReactComponent<AppTanTodoElement, AppTanTodoEvents, Components.AppTanTodo> =
	/*@__PURE__*/ createComponent<AppTanTodoElement, AppTanTodoEvents, Components.AppTanTodo>({
		tagName: "app-tan-todo",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppTanTodo as StencilReactComponent<
			AppTanTodoElement,
			AppTanTodoEvents,
			Components.AppTanTodo
		>,
		serializeShadowRoot,
	});

export type AppTimerEvents = { onIsRunningChange: EventName<AppTimerCustomEvent<boolean>> };

export const AppTimer: StencilReactComponent<AppTimerElement, AppTimerEvents, Components.AppTimer> =
	/*@__PURE__*/ createComponent<AppTimerElement, AppTimerEvents, Components.AppTimer>({
		tagName: "app-timer",
		properties: {
			duration: "duration",
			isRunning: "is-running",
		},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppTimer as StencilReactComponent<
			AppTimerElement,
			AppTimerEvents,
			Components.AppTimer
		>,
		serializeShadowRoot,
	});

export type AppTimerCounterEvents = NonNullable<unknown>;

export const AppTimerCounter: StencilReactComponent<
	AppTimerCounterElement,
	AppTimerCounterEvents,
	Components.AppTimerCounter
> = /*@__PURE__*/ createComponent<AppTimerCounterElement, AppTimerCounterEvents, Components.AppTimerCounter>({
	tagName: "app-timer-counter",
	properties: { timeRemaining: "time-remaining" },
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTimerCounter as StencilReactComponent<
		AppTimerCounterElement,
		AppTimerCounterEvents,
		Components.AppTimerCounter
	>,
	serializeShadowRoot,
});

export type AppTimerHostEvents = NonNullable<unknown>;

export const AppTimerHost: StencilReactComponent<AppTimerHostElement, AppTimerHostEvents, Components.AppTimerHost> =
	/*@__PURE__*/ createComponent<AppTimerHostElement, AppTimerHostEvents, Components.AppTimerHost>({
		tagName: "app-timer-host",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppTimerHost as StencilReactComponent<
			AppTimerHostElement,
			AppTimerHostEvents,
			Components.AppTimerHost
		>,
		serializeShadowRoot,
	});

export type AppTodoEvents = NonNullable<unknown>;

export const AppTodo: StencilReactComponent<AppTodoElement, AppTodoEvents, Components.AppTodo> =
	/*@__PURE__*/ createComponent<AppTodoElement, AppTodoEvents, Components.AppTodo>({
		tagName: "app-todo",
		properties: {},
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.AppTodo as StencilReactComponent<AppTodoElement, AppTodoEvents, Components.AppTodo>,
		serializeShadowRoot,
	});

export type AppTransferStateEvents = NonNullable<unknown>;

export const AppTransferState: StencilReactComponent<
	AppTransferStateElement,
	AppTransferStateEvents,
	Components.AppTransferState
> = /*@__PURE__*/ createComponent<AppTransferStateElement, AppTransferStateEvents, Components.AppTransferState>({
	tagName: "app-transfer-state",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTransferState as StencilReactComponent<
		AppTransferStateElement,
		AppTransferStateEvents,
		Components.AppTransferState
	>,
	serializeShadowRoot,
});

export type AppTranslationProfileEvents = NonNullable<unknown>;

export const AppTranslationProfile: StencilReactComponent<
	AppTranslationProfileElement,
	AppTranslationProfileEvents,
	Components.AppTranslationProfile
> = /*@__PURE__*/ createComponent<
	AppTranslationProfileElement,
	AppTranslationProfileEvents,
	Components.AppTranslationProfile
>({
	tagName: "app-translation-profile",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTranslationProfile as StencilReactComponent<
		AppTranslationProfileElement,
		AppTranslationProfileEvents,
		Components.AppTranslationProfile
	>,
	serializeShadowRoot,
});

export type AppTranslationShellEvents = NonNullable<unknown>;

export const AppTranslationShell: StencilReactComponent<
	AppTranslationShellElement,
	AppTranslationShellEvents,
	Components.AppTranslationShell
> = /*@__PURE__*/ createComponent<
	AppTranslationShellElement,
	AppTranslationShellEvents,
	Components.AppTranslationShell
>({
	tagName: "app-translation-shell",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTranslationShell as StencilReactComponent<
		AppTranslationShellElement,
		AppTranslationShellEvents,
		Components.AppTranslationShell
	>,
	serializeShadowRoot,
});

export type AppTranslationsHostEvents = NonNullable<unknown>;

export const AppTranslationsHost: StencilReactComponent<
	AppTranslationsHostElement,
	AppTranslationsHostEvents,
	Components.AppTranslationsHost
> = /*@__PURE__*/ createComponent<
	AppTranslationsHostElement,
	AppTranslationsHostEvents,
	Components.AppTranslationsHost
>({
	tagName: "app-translations-host",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTranslationsHost as StencilReactComponent<
		AppTranslationsHostElement,
		AppTranslationsHostEvents,
		Components.AppTranslationsHost
	>,
	serializeShadowRoot,
});

export type AppTsQueryHoverPrefetchEvents = NonNullable<unknown>;

export const AppTsQueryHoverPrefetch: StencilReactComponent<
	AppTsQueryHoverPrefetchElement,
	AppTsQueryHoverPrefetchEvents,
	Components.AppTsQueryHoverPrefetch
> = /*@__PURE__*/ createComponent<
	AppTsQueryHoverPrefetchElement,
	AppTsQueryHoverPrefetchEvents,
	Components.AppTsQueryHoverPrefetch
>({
	tagName: "app-ts-query-hover-prefetch",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryHoverPrefetch as StencilReactComponent<
		AppTsQueryHoverPrefetchElement,
		AppTsQueryHoverPrefetchEvents,
		Components.AppTsQueryHoverPrefetch
	>,
	serializeShadowRoot,
});

export type AppTsQueryPostsEvents = NonNullable<unknown>;

export const AppTsQueryPosts: StencilReactComponent<
	AppTsQueryPostsElement,
	AppTsQueryPostsEvents,
	Components.AppTsQueryPosts
> = /*@__PURE__*/ createComponent<AppTsQueryPostsElement, AppTsQueryPostsEvents, Components.AppTsQueryPosts>({
	tagName: "app-ts-query-posts",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryPosts as StencilReactComponent<
		AppTsQueryPostsElement,
		AppTsQueryPostsEvents,
		Components.AppTsQueryPosts
	>,
	serializeShadowRoot,
});

export type AppTsQueryPostsSignalsEvents = NonNullable<unknown>;

export const AppTsQueryPostsSignals: StencilReactComponent<
	AppTsQueryPostsSignalsElement,
	AppTsQueryPostsSignalsEvents,
	Components.AppTsQueryPostsSignals
> = /*@__PURE__*/ createComponent<
	AppTsQueryPostsSignalsElement,
	AppTsQueryPostsSignalsEvents,
	Components.AppTsQueryPostsSignals
>({
	tagName: "app-ts-query-posts-signals",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryPostsSignals as StencilReactComponent<
		AppTsQueryPostsSignalsElement,
		AppTsQueryPostsSignalsEvents,
		Components.AppTsQueryPostsSignals
	>,
	serializeShadowRoot,
});

export type AppTsQueryPrefetchEvents = NonNullable<unknown>;

export const AppTsQueryPrefetch: StencilReactComponent<
	AppTsQueryPrefetchElement,
	AppTsQueryPrefetchEvents,
	Components.AppTsQueryPrefetch
> = /*@__PURE__*/ createComponent<AppTsQueryPrefetchElement, AppTsQueryPrefetchEvents, Components.AppTsQueryPrefetch>({
	tagName: "app-ts-query-prefetch",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryPrefetch as StencilReactComponent<
		AppTsQueryPrefetchElement,
		AppTsQueryPrefetchEvents,
		Components.AppTsQueryPrefetch
	>,
	serializeShadowRoot,
});

export type AppTsQueryPrefetchDemoEvents = NonNullable<unknown>;

export const AppTsQueryPrefetchDemo: StencilReactComponent<
	AppTsQueryPrefetchDemoElement,
	AppTsQueryPrefetchDemoEvents,
	Components.AppTsQueryPrefetchDemo
> = /*@__PURE__*/ createComponent<
	AppTsQueryPrefetchDemoElement,
	AppTsQueryPrefetchDemoEvents,
	Components.AppTsQueryPrefetchDemo
>({
	tagName: "app-ts-query-prefetch-demo",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryPrefetchDemo as StencilReactComponent<
		AppTsQueryPrefetchDemoElement,
		AppTsQueryPrefetchDemoEvents,
		Components.AppTsQueryPrefetchDemo
	>,
	serializeShadowRoot,
});

export type AppTsQueryPrefetchReuseEvents = NonNullable<unknown>;

export const AppTsQueryPrefetchReuse: StencilReactComponent<
	AppTsQueryPrefetchReuseElement,
	AppTsQueryPrefetchReuseEvents,
	Components.AppTsQueryPrefetchReuse
> = /*@__PURE__*/ createComponent<
	AppTsQueryPrefetchReuseElement,
	AppTsQueryPrefetchReuseEvents,
	Components.AppTsQueryPrefetchReuse
>({
	tagName: "app-ts-query-prefetch-reuse",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryPrefetchReuse as StencilReactComponent<
		AppTsQueryPrefetchReuseElement,
		AppTsQueryPrefetchReuseEvents,
		Components.AppTsQueryPrefetchReuse
	>,
	serializeShadowRoot,
});

export type AppTsQueryUseQueriesDemoEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesDemo: StencilReactComponent<
	AppTsQueryUseQueriesDemoElement,
	AppTsQueryUseQueriesDemoEvents,
	Components.AppTsQueryUseQueriesDemo
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesDemoElement,
	AppTsQueryUseQueriesDemoEvents,
	Components.AppTsQueryUseQueriesDemo
>({
	tagName: "app-ts-query-use-queries-demo",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryUseQueriesDemo as StencilReactComponent<
		AppTsQueryUseQueriesDemoElement,
		AppTsQueryUseQueriesDemoEvents,
		Components.AppTsQueryUseQueriesDemo
	>,
	serializeShadowRoot,
});

export type AppTsQueryUseQueriesInlineEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesInline: StencilReactComponent<
	AppTsQueryUseQueriesInlineElement,
	AppTsQueryUseQueriesInlineEvents,
	Components.AppTsQueryUseQueriesInline
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesInlineElement,
	AppTsQueryUseQueriesInlineEvents,
	Components.AppTsQueryUseQueriesInline
>({
	tagName: "app-ts-query-use-queries-inline",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryUseQueriesInline as StencilReactComponent<
		AppTsQueryUseQueriesInlineElement,
		AppTsQueryUseQueriesInlineEvents,
		Components.AppTsQueryUseQueriesInline
	>,
	serializeShadowRoot,
});

export type AppTsQueryUseQueriesReuseEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesReuse: StencilReactComponent<
	AppTsQueryUseQueriesReuseElement,
	AppTsQueryUseQueriesReuseEvents,
	Components.AppTsQueryUseQueriesReuse
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesReuseElement,
	AppTsQueryUseQueriesReuseEvents,
	Components.AppTsQueryUseQueriesReuse
>({
	tagName: "app-ts-query-use-queries-reuse",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryUseQueriesReuse as StencilReactComponent<
		AppTsQueryUseQueriesReuseElement,
		AppTsQueryUseQueriesReuseEvents,
		Components.AppTsQueryUseQueriesReuse
	>,
	serializeShadowRoot,
});

export type AppTsQueryUseQueriesSignalsEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesSignals: StencilReactComponent<
	AppTsQueryUseQueriesSignalsElement,
	AppTsQueryUseQueriesSignalsEvents,
	Components.AppTsQueryUseQueriesSignals
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesSignalsElement,
	AppTsQueryUseQueriesSignalsEvents,
	Components.AppTsQueryUseQueriesSignals
>({
	tagName: "app-ts-query-use-queries-signals",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryUseQueriesSignals as StencilReactComponent<
		AppTsQueryUseQueriesSignalsElement,
		AppTsQueryUseQueriesSignalsEvents,
		Components.AppTsQueryUseQueriesSignals
	>,
	serializeShadowRoot,
});

export type AppTsQueryUseQueriesSignalsCombineEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesSignalsCombine: StencilReactComponent<
	AppTsQueryUseQueriesSignalsCombineElement,
	AppTsQueryUseQueriesSignalsCombineEvents,
	Components.AppTsQueryUseQueriesSignalsCombine
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesSignalsCombineElement,
	AppTsQueryUseQueriesSignalsCombineEvents,
	Components.AppTsQueryUseQueriesSignalsCombine
>({
	tagName: "app-ts-query-use-queries-signals-combine",
	properties: {},
	hydrateModule:
		typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
	clientModule: clientComponents.AppTsQueryUseQueriesSignalsCombine as StencilReactComponent<
		AppTsQueryUseQueriesSignalsCombineElement,
		AppTsQueryUseQueriesSignalsCombineEvents,
		Components.AppTsQueryUseQueriesSignalsCombine
	>,
	serializeShadowRoot,
});

export type SsvComposeEvents = { onComposeEvent: EventName<SsvComposeCustomEvent<ComposeEventDetail>> };

export const SsvCompose: StencilReactComponent<SsvComposeElement, SsvComposeEvents, Components.SsvCompose> =
	/*@__PURE__*/ createComponent<SsvComposeElement, SsvComposeEvents, Components.SsvCompose>({
		tagName: "ssv-compose",
		properties: { name: "name" },
		hydrateModule:
			typeof window === "undefined" ? (import("@app/stencil-playground/hydrate") as Promise<HydrateModule>) : undefined,
		clientModule: clientComponents.SsvCompose as StencilReactComponent<
			SsvComposeElement,
			SsvComposeEvents,
			Components.SsvCompose
		>,
		serializeShadowRoot,
	});
