"use client";

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import {
	type AppLolChampionCardCustomEvent,
	type AppLolChampionFilterCustomEvent,
	type AppLolLobbyListCustomEvent,
	type AppTimerCustomEvent,
	type ChampionRole,
	type ComposeEventDetail,
	type LobbyJoinEvent,
	type SsvComposeCustomEvent,
} from "@app/stencil-playground";
import type { Components } from "@app/stencil-playground/dist/components";
import {
	AppComposeDemo as AppComposeDemoElement,
	defineCustomElement as defineAppComposeDemo,
} from "@app/stencil-playground/dist/components/app-compose-demo.js";
import {
	AppCounter as AppCounterElement,
	defineCustomElement as defineAppCounter,
} from "@app/stencil-playground/dist/components/app-counter.js";
import {
	AppCtxCounterGroup as AppCtxCounterGroupElement,
	defineCustomElement as defineAppCtxCounterGroup,
} from "@app/stencil-playground/dist/components/app-ctx-counter-group.js";
import {
	AppCtxCounter as AppCtxCounterElement,
	defineCustomElement as defineAppCtxCounter,
} from "@app/stencil-playground/dist/components/app-ctx-counter.js";
import {
	AppEffectDemo as AppEffectDemoElement,
	defineCustomElement as defineAppEffectDemo,
} from "@app/stencil-playground/dist/components/app-effect-demo.js";
import {
	AppIntersectionObserver as AppIntersectionObserverElement,
	defineCustomElement as defineAppIntersectionObserver,
} from "@app/stencil-playground/dist/components/app-intersection-observer.js";
import {
	AppLifecycleDemo as AppLifecycleDemoElement,
	defineCustomElement as defineAppLifecycleDemo,
} from "@app/stencil-playground/dist/components/app-lifecycle-demo.js";
import {
	AppLolChampionCard as AppLolChampionCardElement,
	defineCustomElement as defineAppLolChampionCard,
} from "@app/stencil-playground/dist/components/app-lol-champion-card.js";
import {
	AppLolChampionFilter as AppLolChampionFilterElement,
	defineCustomElement as defineAppLolChampionFilter,
} from "@app/stencil-playground/dist/components/app-lol-champion-filter.js";
import {
	AppLolChampionPool as AppLolChampionPoolElement,
	defineCustomElement as defineAppLolChampionPool,
} from "@app/stencil-playground/dist/components/app-lol-champion-pool.js";
import {
	AppLolDraftArea as AppLolDraftAreaElement,
	defineCustomElement as defineAppLolDraftArea,
} from "@app/stencil-playground/dist/components/app-lol-draft-area.js";
import {
	AppLolDraftHeroCard as AppLolDraftHeroCardElement,
	defineCustomElement as defineAppLolDraftHeroCard,
} from "@app/stencil-playground/dist/components/app-lol-draft-hero-card.js";
import {
	AppLolDraftInfo as AppLolDraftInfoElement,
	defineCustomElement as defineAppLolDraftInfo,
} from "@app/stencil-playground/dist/components/app-lol-draft-info.js";
import {
	AppLolDraftLayout as AppLolDraftLayoutElement,
	defineCustomElement as defineAppLolDraftLayout,
} from "@app/stencil-playground/dist/components/app-lol-draft-layout.js";
import {
	AppLolDraftLobbyHost as AppLolDraftLobbyHostElement,
	defineCustomElement as defineAppLolDraftLobbyHost,
} from "@app/stencil-playground/dist/components/app-lol-draft-lobby-host.js";
import {
	AppLolDraftSlot as AppLolDraftSlotElement,
	defineCustomElement as defineAppLolDraftSlot,
} from "@app/stencil-playground/dist/components/app-lol-draft-slot.js";
import {
	AppLolLobbyList as AppLolLobbyListElement,
	defineCustomElement as defineAppLolLobbyList,
} from "@app/stencil-playground/dist/components/app-lol-lobby-list.js";
import {
	AppLolNotification as AppLolNotificationElement,
	defineCustomElement as defineAppLolNotification,
} from "@app/stencil-playground/dist/components/app-lol-notification.js";
import {
	AppLolTeamSection as AppLolTeamSectionElement,
	defineCustomElement as defineAppLolTeamSection,
} from "@app/stencil-playground/dist/components/app-lol-team-section.js";
import {
	AppMouseHost as AppMouseHostElement,
	defineCustomElement as defineAppMouseHost,
} from "@app/stencil-playground/dist/components/app-mouse-host.js";
import {
	AppMutationObserver as AppMutationObserverElement,
	defineCustomElement as defineAppMutationObserver,
} from "@app/stencil-playground/dist/components/app-mutation-observer.js";
import {
	AppResizeObserver as AppResizeObserverElement,
	defineCustomElement as defineAppResizeObserver,
} from "@app/stencil-playground/dist/components/app-resize-observer.js";
import {
	AppSignalsComputedPrevious as AppSignalsComputedPreviousElement,
	defineCustomElement as defineAppSignalsComputedPrevious,
} from "@app/stencil-playground/dist/components/app-signals-computed-previous.js";
import {
	AppSignalsCounter as AppSignalsCounterElement,
	defineCustomElement as defineAppSignalsCounter,
} from "@app/stencil-playground/dist/components/app-signals-counter.js";
import {
	AppSignalsDerivedAsync as AppSignalsDerivedAsyncElement,
	defineCustomElement as defineAppSignalsDerivedAsync,
} from "@app/stencil-playground/dist/components/app-signals-derived-async.js";
import {
	AppSignalsMouseEvent as AppSignalsMouseEventElement,
	defineCustomElement as defineAppSignalsMouseEvent,
} from "@app/stencil-playground/dist/components/app-signals-mouse-event.js";
import {
	AppSignalsObserverSignals as AppSignalsObserverSignalsElement,
	defineCustomElement as defineAppSignalsObserverSignals,
} from "@app/stencil-playground/dist/components/app-signals-observer-signals.js";
import {
	AppSignalsTodo as AppSignalsTodoElement,
	defineCustomElement as defineAppSignalsTodo,
} from "@app/stencil-playground/dist/components/app-signals-todo.js";
import {
	AppStartupContextInspector as AppStartupContextInspectorElement,
	defineCustomElement as defineAppStartupContextInspector,
} from "@app/stencil-playground/dist/components/app-startup-context-inspector.js";
import {
	AppStartupContextProvider as AppStartupContextProviderElement,
	defineCustomElement as defineAppStartupContextProvider,
} from "@app/stencil-playground/dist/components/app-startup-context-provider.js";
import {
	AppTanCounter as AppTanCounterElement,
	defineCustomElement as defineAppTanCounter,
} from "@app/stencil-playground/dist/components/app-tan-counter.js";
import {
	AppTanTodo as AppTanTodoElement,
	defineCustomElement as defineAppTanTodo,
} from "@app/stencil-playground/dist/components/app-tan-todo.js";
import {
	AppTimerCounter as AppTimerCounterElement,
	defineCustomElement as defineAppTimerCounter,
} from "@app/stencil-playground/dist/components/app-timer-counter.js";
import {
	AppTimerHost as AppTimerHostElement,
	defineCustomElement as defineAppTimerHost,
} from "@app/stencil-playground/dist/components/app-timer-host.js";
import {
	AppTimer as AppTimerElement,
	defineCustomElement as defineAppTimer,
} from "@app/stencil-playground/dist/components/app-timer.js";
import {
	AppTodo as AppTodoElement,
	defineCustomElement as defineAppTodo,
} from "@app/stencil-playground/dist/components/app-todo.js";
import {
	AppTransferState as AppTransferStateElement,
	defineCustomElement as defineAppTransferState,
} from "@app/stencil-playground/dist/components/app-transfer-state.js";
import {
	AppTranslationProfile as AppTranslationProfileElement,
	defineCustomElement as defineAppTranslationProfile,
} from "@app/stencil-playground/dist/components/app-translation-profile.js";
import {
	AppTranslationShell as AppTranslationShellElement,
	defineCustomElement as defineAppTranslationShell,
} from "@app/stencil-playground/dist/components/app-translation-shell.js";
import {
	AppTranslationsHost as AppTranslationsHostElement,
	defineCustomElement as defineAppTranslationsHost,
} from "@app/stencil-playground/dist/components/app-translations-host.js";
import {
	AppTsQueryHoverPrefetch as AppTsQueryHoverPrefetchElement,
	defineCustomElement as defineAppTsQueryHoverPrefetch,
} from "@app/stencil-playground/dist/components/app-ts-query-hover-prefetch.js";
import {
	AppTsQueryPostsSignals as AppTsQueryPostsSignalsElement,
	defineCustomElement as defineAppTsQueryPostsSignals,
} from "@app/stencil-playground/dist/components/app-ts-query-posts-signals.js";
import {
	AppTsQueryPosts as AppTsQueryPostsElement,
	defineCustomElement as defineAppTsQueryPosts,
} from "@app/stencil-playground/dist/components/app-ts-query-posts.js";
import {
	AppTsQueryPrefetchDemo as AppTsQueryPrefetchDemoElement,
	defineCustomElement as defineAppTsQueryPrefetchDemo,
} from "@app/stencil-playground/dist/components/app-ts-query-prefetch-demo.js";
import {
	AppTsQueryPrefetchReuse as AppTsQueryPrefetchReuseElement,
	defineCustomElement as defineAppTsQueryPrefetchReuse,
} from "@app/stencil-playground/dist/components/app-ts-query-prefetch-reuse.js";
import {
	AppTsQueryPrefetch as AppTsQueryPrefetchElement,
	defineCustomElement as defineAppTsQueryPrefetch,
} from "@app/stencil-playground/dist/components/app-ts-query-prefetch.js";
import {
	AppTsQueryUseQueriesDemo as AppTsQueryUseQueriesDemoElement,
	defineCustomElement as defineAppTsQueryUseQueriesDemo,
} from "@app/stencil-playground/dist/components/app-ts-query-use-queries-demo.js";
import {
	AppTsQueryUseQueriesInline as AppTsQueryUseQueriesInlineElement,
	defineCustomElement as defineAppTsQueryUseQueriesInline,
} from "@app/stencil-playground/dist/components/app-ts-query-use-queries-inline.js";
import {
	AppTsQueryUseQueriesReuse as AppTsQueryUseQueriesReuseElement,
	defineCustomElement as defineAppTsQueryUseQueriesReuse,
} from "@app/stencil-playground/dist/components/app-ts-query-use-queries-reuse.js";
import {
	AppTsQueryUseQueriesSignalsCombine as AppTsQueryUseQueriesSignalsCombineElement,
	defineCustomElement as defineAppTsQueryUseQueriesSignalsCombine,
} from "@app/stencil-playground/dist/components/app-ts-query-use-queries-signals-combine.js";
import {
	AppTsQueryUseQueriesSignals as AppTsQueryUseQueriesSignalsElement,
	defineCustomElement as defineAppTsQueryUseQueriesSignals,
} from "@app/stencil-playground/dist/components/app-ts-query-use-queries-signals.js";
import {
	SsvCompose as SsvComposeElement,
	defineCustomElement as defineSsvCompose,
} from "@app/stencil-playground/dist/components/ssv-compose.js";
import type { EventName, StencilReactComponent } from "@stencil/react-output-target/runtime";
import { createComponent } from "@stencil/react-output-target/runtime";
import React from "react";

export type AppComposeDemoEvents = NonNullable<unknown>;

export const AppComposeDemo: StencilReactComponent<
	AppComposeDemoElement,
	AppComposeDemoEvents,
	Components.AppComposeDemo
> = /*@__PURE__*/ createComponent<AppComposeDemoElement, AppComposeDemoEvents, Components.AppComposeDemo>({
	tagName: "app-compose-demo",
	elementClass: AppComposeDemoElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppComposeDemoEvents,
	defineCustomElement: defineAppComposeDemo,
});

export type AppCounterEvents = NonNullable<unknown>;

export const AppCounter: StencilReactComponent<AppCounterElement, AppCounterEvents, Components.AppCounter> =
	/*@__PURE__*/ createComponent<AppCounterElement, AppCounterEvents, Components.AppCounter>({
		tagName: "app-counter",
		elementClass: AppCounterElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppCounterEvents,
		defineCustomElement: defineAppCounter,
	});

export type AppCtxCounterEvents = NonNullable<unknown>;

export const AppCtxCounter: StencilReactComponent<AppCtxCounterElement, AppCtxCounterEvents, Components.AppCtxCounter> =
	/*@__PURE__*/ createComponent<AppCtxCounterElement, AppCtxCounterEvents, Components.AppCtxCounter>({
		tagName: "app-ctx-counter",
		elementClass: AppCtxCounterElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppCtxCounterEvents,
		defineCustomElement: defineAppCtxCounter,
	});

export type AppCtxCounterGroupEvents = NonNullable<unknown>;

export const AppCtxCounterGroup: StencilReactComponent<
	AppCtxCounterGroupElement,
	AppCtxCounterGroupEvents,
	Components.AppCtxCounterGroup
> = /*@__PURE__*/ createComponent<AppCtxCounterGroupElement, AppCtxCounterGroupEvents, Components.AppCtxCounterGroup>({
	tagName: "app-ctx-counter-group",
	elementClass: AppCtxCounterGroupElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppCtxCounterGroupEvents,
	defineCustomElement: defineAppCtxCounterGroup,
});

export type AppEffectDemoEvents = NonNullable<unknown>;

export const AppEffectDemo: StencilReactComponent<AppEffectDemoElement, AppEffectDemoEvents, Components.AppEffectDemo> =
	/*@__PURE__*/ createComponent<AppEffectDemoElement, AppEffectDemoEvents, Components.AppEffectDemo>({
		tagName: "app-effect-demo",
		elementClass: AppEffectDemoElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppEffectDemoEvents,
		defineCustomElement: defineAppEffectDemo,
	});

export type AppIntersectionObserverEvents = NonNullable<unknown>;

export const AppIntersectionObserver: StencilReactComponent<
	AppIntersectionObserverElement,
	AppIntersectionObserverEvents,
	Components.AppIntersectionObserver
> = /*@__PURE__*/ createComponent<
	AppIntersectionObserverElement,
	AppIntersectionObserverEvents,
	Components.AppIntersectionObserver
>({
	tagName: "app-intersection-observer",
	elementClass: AppIntersectionObserverElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppIntersectionObserverEvents,
	defineCustomElement: defineAppIntersectionObserver,
});

export type AppLifecycleDemoEvents = NonNullable<unknown>;

export const AppLifecycleDemo: StencilReactComponent<
	AppLifecycleDemoElement,
	AppLifecycleDemoEvents,
	Components.AppLifecycleDemo
> = /*@__PURE__*/ createComponent<AppLifecycleDemoElement, AppLifecycleDemoEvents, Components.AppLifecycleDemo>({
	tagName: "app-lifecycle-demo",
	elementClass: AppLifecycleDemoElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLifecycleDemoEvents,
	defineCustomElement: defineAppLifecycleDemo,
});

export type AppLolChampionCardEvents = { onChampionSelect: EventName<AppLolChampionCardCustomEvent<string>> };

export const AppLolChampionCard: StencilReactComponent<
	AppLolChampionCardElement,
	AppLolChampionCardEvents,
	Components.AppLolChampionCard
> = /*@__PURE__*/ createComponent<AppLolChampionCardElement, AppLolChampionCardEvents, Components.AppLolChampionCard>({
	tagName: "app-lol-champion-card",
	elementClass: AppLolChampionCardElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: { onChampionSelect: "championSelect" } as AppLolChampionCardEvents,
	defineCustomElement: defineAppLolChampionCard,
});

export type AppLolChampionFilterEvents = {
	onSearchChange: EventName<AppLolChampionFilterCustomEvent<string>>;
	onRoleToggle: EventName<AppLolChampionFilterCustomEvent<ChampionRole>>;
	onClearFilters: EventName<AppLolChampionFilterCustomEvent<void>>;
};

export const AppLolChampionFilter: StencilReactComponent<
	AppLolChampionFilterElement,
	AppLolChampionFilterEvents,
	Components.AppLolChampionFilter
> = /*@__PURE__*/ createComponent<
	AppLolChampionFilterElement,
	AppLolChampionFilterEvents,
	Components.AppLolChampionFilter
>({
	tagName: "app-lol-champion-filter",
	elementClass: AppLolChampionFilterElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {
		onSearchChange: "searchChange",
		onRoleToggle: "roleToggle",
		onClearFilters: "clearFilters",
	} as AppLolChampionFilterEvents,
	defineCustomElement: defineAppLolChampionFilter,
});

export type AppLolChampionPoolEvents = NonNullable<unknown>;

export const AppLolChampionPool: StencilReactComponent<
	AppLolChampionPoolElement,
	AppLolChampionPoolEvents,
	Components.AppLolChampionPool
> = /*@__PURE__*/ createComponent<AppLolChampionPoolElement, AppLolChampionPoolEvents, Components.AppLolChampionPool>({
	tagName: "app-lol-champion-pool",
	elementClass: AppLolChampionPoolElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolChampionPoolEvents,
	defineCustomElement: defineAppLolChampionPool,
});

export type AppLolDraftAreaEvents = NonNullable<unknown>;

export const AppLolDraftArea: StencilReactComponent<
	AppLolDraftAreaElement,
	AppLolDraftAreaEvents,
	Components.AppLolDraftArea
> = /*@__PURE__*/ createComponent<AppLolDraftAreaElement, AppLolDraftAreaEvents, Components.AppLolDraftArea>({
	tagName: "app-lol-draft-area",
	elementClass: AppLolDraftAreaElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolDraftAreaEvents,
	defineCustomElement: defineAppLolDraftArea,
});

export type AppLolDraftHeroCardEvents = NonNullable<unknown>;

export const AppLolDraftHeroCard: StencilReactComponent<
	AppLolDraftHeroCardElement,
	AppLolDraftHeroCardEvents,
	Components.AppLolDraftHeroCard
> = /*@__PURE__*/ createComponent<
	AppLolDraftHeroCardElement,
	AppLolDraftHeroCardEvents,
	Components.AppLolDraftHeroCard
>({
	tagName: "app-lol-draft-hero-card",
	elementClass: AppLolDraftHeroCardElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolDraftHeroCardEvents,
	defineCustomElement: defineAppLolDraftHeroCard,
});

export type AppLolDraftInfoEvents = NonNullable<unknown>;

export const AppLolDraftInfo: StencilReactComponent<
	AppLolDraftInfoElement,
	AppLolDraftInfoEvents,
	Components.AppLolDraftInfo
> = /*@__PURE__*/ createComponent<AppLolDraftInfoElement, AppLolDraftInfoEvents, Components.AppLolDraftInfo>({
	tagName: "app-lol-draft-info",
	elementClass: AppLolDraftInfoElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolDraftInfoEvents,
	defineCustomElement: defineAppLolDraftInfo,
});

export type AppLolDraftLayoutEvents = NonNullable<unknown>;

export const AppLolDraftLayout: StencilReactComponent<
	AppLolDraftLayoutElement,
	AppLolDraftLayoutEvents,
	Components.AppLolDraftLayout
> = /*@__PURE__*/ createComponent<AppLolDraftLayoutElement, AppLolDraftLayoutEvents, Components.AppLolDraftLayout>({
	tagName: "app-lol-draft-layout",
	elementClass: AppLolDraftLayoutElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolDraftLayoutEvents,
	defineCustomElement: defineAppLolDraftLayout,
});

export type AppLolDraftLobbyHostEvents = NonNullable<unknown>;

export const AppLolDraftLobbyHost: StencilReactComponent<
	AppLolDraftLobbyHostElement,
	AppLolDraftLobbyHostEvents,
	Components.AppLolDraftLobbyHost
> = /*@__PURE__*/ createComponent<
	AppLolDraftLobbyHostElement,
	AppLolDraftLobbyHostEvents,
	Components.AppLolDraftLobbyHost
>({
	tagName: "app-lol-draft-lobby-host",
	elementClass: AppLolDraftLobbyHostElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolDraftLobbyHostEvents,
	defineCustomElement: defineAppLolDraftLobbyHost,
});

export type AppLolDraftSlotEvents = NonNullable<unknown>;

export const AppLolDraftSlot: StencilReactComponent<
	AppLolDraftSlotElement,
	AppLolDraftSlotEvents,
	Components.AppLolDraftSlot
> = /*@__PURE__*/ createComponent<AppLolDraftSlotElement, AppLolDraftSlotEvents, Components.AppLolDraftSlot>({
	tagName: "app-lol-draft-slot",
	elementClass: AppLolDraftSlotElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolDraftSlotEvents,
	defineCustomElement: defineAppLolDraftSlot,
});

export type AppLolLobbyListEvents = {
	onAppCreate: EventName<AppLolLobbyListCustomEvent<LobbyJoinEvent>>;
	onAppJoin: EventName<AppLolLobbyListCustomEvent<LobbyJoinEvent>>;
};

export const AppLolLobbyList: StencilReactComponent<
	AppLolLobbyListElement,
	AppLolLobbyListEvents,
	Components.AppLolLobbyList
> = /*@__PURE__*/ createComponent<AppLolLobbyListElement, AppLolLobbyListEvents, Components.AppLolLobbyList>({
	tagName: "app-lol-lobby-list",
	elementClass: AppLolLobbyListElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {
		onAppCreate: "appCreate",
		onAppJoin: "appJoin",
	} as AppLolLobbyListEvents,
	defineCustomElement: defineAppLolLobbyList,
});

export type AppLolNotificationEvents = NonNullable<unknown>;

export const AppLolNotification: StencilReactComponent<
	AppLolNotificationElement,
	AppLolNotificationEvents,
	Components.AppLolNotification
> = /*@__PURE__*/ createComponent<AppLolNotificationElement, AppLolNotificationEvents, Components.AppLolNotification>({
	tagName: "app-lol-notification",
	elementClass: AppLolNotificationElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolNotificationEvents,
	defineCustomElement: defineAppLolNotification,
});

export type AppLolTeamSectionEvents = NonNullable<unknown>;

export const AppLolTeamSection: StencilReactComponent<
	AppLolTeamSectionElement,
	AppLolTeamSectionEvents,
	Components.AppLolTeamSection
> = /*@__PURE__*/ createComponent<AppLolTeamSectionElement, AppLolTeamSectionEvents, Components.AppLolTeamSection>({
	tagName: "app-lol-team-section",
	elementClass: AppLolTeamSectionElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppLolTeamSectionEvents,
	defineCustomElement: defineAppLolTeamSection,
});

export type AppMouseHostEvents = NonNullable<unknown>;

export const AppMouseHost: StencilReactComponent<AppMouseHostElement, AppMouseHostEvents, Components.AppMouseHost> =
	/*@__PURE__*/ createComponent<AppMouseHostElement, AppMouseHostEvents, Components.AppMouseHost>({
		tagName: "app-mouse-host",
		elementClass: AppMouseHostElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppMouseHostEvents,
		defineCustomElement: defineAppMouseHost,
	});

export type AppMutationObserverEvents = NonNullable<unknown>;

export const AppMutationObserver: StencilReactComponent<
	AppMutationObserverElement,
	AppMutationObserverEvents,
	Components.AppMutationObserver
> = /*@__PURE__*/ createComponent<
	AppMutationObserverElement,
	AppMutationObserverEvents,
	Components.AppMutationObserver
>({
	tagName: "app-mutation-observer",
	elementClass: AppMutationObserverElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppMutationObserverEvents,
	defineCustomElement: defineAppMutationObserver,
});

export type AppResizeObserverEvents = NonNullable<unknown>;

export const AppResizeObserver: StencilReactComponent<
	AppResizeObserverElement,
	AppResizeObserverEvents,
	Components.AppResizeObserver
> = /*@__PURE__*/ createComponent<AppResizeObserverElement, AppResizeObserverEvents, Components.AppResizeObserver>({
	tagName: "app-resize-observer",
	elementClass: AppResizeObserverElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppResizeObserverEvents,
	defineCustomElement: defineAppResizeObserver,
});

export type AppSignalsComputedPreviousEvents = NonNullable<unknown>;

export const AppSignalsComputedPrevious: StencilReactComponent<
	AppSignalsComputedPreviousElement,
	AppSignalsComputedPreviousEvents,
	Components.AppSignalsComputedPrevious
> = /*@__PURE__*/ createComponent<
	AppSignalsComputedPreviousElement,
	AppSignalsComputedPreviousEvents,
	Components.AppSignalsComputedPrevious
>({
	tagName: "app-signals-computed-previous",
	elementClass: AppSignalsComputedPreviousElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppSignalsComputedPreviousEvents,
	defineCustomElement: defineAppSignalsComputedPrevious,
});

export type AppSignalsCounterEvents = NonNullable<unknown>;

export const AppSignalsCounter: StencilReactComponent<
	AppSignalsCounterElement,
	AppSignalsCounterEvents,
	Components.AppSignalsCounter
> = /*@__PURE__*/ createComponent<AppSignalsCounterElement, AppSignalsCounterEvents, Components.AppSignalsCounter>({
	tagName: "app-signals-counter",
	elementClass: AppSignalsCounterElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppSignalsCounterEvents,
	defineCustomElement: defineAppSignalsCounter,
});

export type AppSignalsDerivedAsyncEvents = NonNullable<unknown>;

export const AppSignalsDerivedAsync: StencilReactComponent<
	AppSignalsDerivedAsyncElement,
	AppSignalsDerivedAsyncEvents,
	Components.AppSignalsDerivedAsync
> = /*@__PURE__*/ createComponent<
	AppSignalsDerivedAsyncElement,
	AppSignalsDerivedAsyncEvents,
	Components.AppSignalsDerivedAsync
>({
	tagName: "app-signals-derived-async",
	elementClass: AppSignalsDerivedAsyncElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppSignalsDerivedAsyncEvents,
	defineCustomElement: defineAppSignalsDerivedAsync,
});

export type AppSignalsMouseEventEvents = NonNullable<unknown>;

export const AppSignalsMouseEvent: StencilReactComponent<
	AppSignalsMouseEventElement,
	AppSignalsMouseEventEvents,
	Components.AppSignalsMouseEvent
> = /*@__PURE__*/ createComponent<
	AppSignalsMouseEventElement,
	AppSignalsMouseEventEvents,
	Components.AppSignalsMouseEvent
>({
	tagName: "app-signals-mouse-event",
	elementClass: AppSignalsMouseEventElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppSignalsMouseEventEvents,
	defineCustomElement: defineAppSignalsMouseEvent,
});

export type AppSignalsObserverSignalsEvents = NonNullable<unknown>;

export const AppSignalsObserverSignals: StencilReactComponent<
	AppSignalsObserverSignalsElement,
	AppSignalsObserverSignalsEvents,
	Components.AppSignalsObserverSignals
> = /*@__PURE__*/ createComponent<
	AppSignalsObserverSignalsElement,
	AppSignalsObserverSignalsEvents,
	Components.AppSignalsObserverSignals
>({
	tagName: "app-signals-observer-signals",
	elementClass: AppSignalsObserverSignalsElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppSignalsObserverSignalsEvents,
	defineCustomElement: defineAppSignalsObserverSignals,
});

export type AppSignalsTodoEvents = NonNullable<unknown>;

export const AppSignalsTodo: StencilReactComponent<
	AppSignalsTodoElement,
	AppSignalsTodoEvents,
	Components.AppSignalsTodo
> = /*@__PURE__*/ createComponent<AppSignalsTodoElement, AppSignalsTodoEvents, Components.AppSignalsTodo>({
	tagName: "app-signals-todo",
	elementClass: AppSignalsTodoElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppSignalsTodoEvents,
	defineCustomElement: defineAppSignalsTodo,
});

export type AppStartupContextInspectorEvents = NonNullable<unknown>;

export const AppStartupContextInspector: StencilReactComponent<
	AppStartupContextInspectorElement,
	AppStartupContextInspectorEvents,
	Components.AppStartupContextInspector
> = /*@__PURE__*/ createComponent<
	AppStartupContextInspectorElement,
	AppStartupContextInspectorEvents,
	Components.AppStartupContextInspector
>({
	tagName: "app-startup-context-inspector",
	elementClass: AppStartupContextInspectorElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppStartupContextInspectorEvents,
	defineCustomElement: defineAppStartupContextInspector,
});

export type AppStartupContextProviderEvents = NonNullable<unknown>;

export const AppStartupContextProvider: StencilReactComponent<
	AppStartupContextProviderElement,
	AppStartupContextProviderEvents,
	Components.AppStartupContextProvider
> = /*@__PURE__*/ createComponent<
	AppStartupContextProviderElement,
	AppStartupContextProviderEvents,
	Components.AppStartupContextProvider
>({
	tagName: "app-startup-context-provider",
	elementClass: AppStartupContextProviderElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppStartupContextProviderEvents,
	defineCustomElement: defineAppStartupContextProvider,
});

export type AppTanCounterEvents = NonNullable<unknown>;

export const AppTanCounter: StencilReactComponent<AppTanCounterElement, AppTanCounterEvents, Components.AppTanCounter> =
	/*@__PURE__*/ createComponent<AppTanCounterElement, AppTanCounterEvents, Components.AppTanCounter>({
		tagName: "app-tan-counter",
		elementClass: AppTanCounterElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppTanCounterEvents,
		defineCustomElement: defineAppTanCounter,
	});

export type AppTanTodoEvents = NonNullable<unknown>;

export const AppTanTodo: StencilReactComponent<AppTanTodoElement, AppTanTodoEvents, Components.AppTanTodo> =
	/*@__PURE__*/ createComponent<AppTanTodoElement, AppTanTodoEvents, Components.AppTanTodo>({
		tagName: "app-tan-todo",
		elementClass: AppTanTodoElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppTanTodoEvents,
		defineCustomElement: defineAppTanTodo,
	});

export type AppTimerEvents = { onIsRunningChange: EventName<AppTimerCustomEvent<boolean>> };

export const AppTimer: StencilReactComponent<AppTimerElement, AppTimerEvents, Components.AppTimer> =
	/*@__PURE__*/ createComponent<AppTimerElement, AppTimerEvents, Components.AppTimer>({
		tagName: "app-timer",
		elementClass: AppTimerElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: { onIsRunningChange: "isRunningChange" } as AppTimerEvents,
		defineCustomElement: defineAppTimer,
	});

export type AppTimerCounterEvents = NonNullable<unknown>;

export const AppTimerCounter: StencilReactComponent<
	AppTimerCounterElement,
	AppTimerCounterEvents,
	Components.AppTimerCounter
> = /*@__PURE__*/ createComponent<AppTimerCounterElement, AppTimerCounterEvents, Components.AppTimerCounter>({
	tagName: "app-timer-counter",
	elementClass: AppTimerCounterElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTimerCounterEvents,
	defineCustomElement: defineAppTimerCounter,
});

export type AppTimerHostEvents = NonNullable<unknown>;

export const AppTimerHost: StencilReactComponent<AppTimerHostElement, AppTimerHostEvents, Components.AppTimerHost> =
	/*@__PURE__*/ createComponent<AppTimerHostElement, AppTimerHostEvents, Components.AppTimerHost>({
		tagName: "app-timer-host",
		elementClass: AppTimerHostElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppTimerHostEvents,
		defineCustomElement: defineAppTimerHost,
	});

export type AppTodoEvents = NonNullable<unknown>;

export const AppTodo: StencilReactComponent<AppTodoElement, AppTodoEvents, Components.AppTodo> =
	/*@__PURE__*/ createComponent<AppTodoElement, AppTodoEvents, Components.AppTodo>({
		tagName: "app-todo",
		elementClass: AppTodoElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: {} as AppTodoEvents,
		defineCustomElement: defineAppTodo,
	});

export type AppTransferStateEvents = NonNullable<unknown>;

export const AppTransferState: StencilReactComponent<
	AppTransferStateElement,
	AppTransferStateEvents,
	Components.AppTransferState
> = /*@__PURE__*/ createComponent<AppTransferStateElement, AppTransferStateEvents, Components.AppTransferState>({
	tagName: "app-transfer-state",
	elementClass: AppTransferStateElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTransferStateEvents,
	defineCustomElement: defineAppTransferState,
});

export type AppTranslationProfileEvents = NonNullable<unknown>;

export const AppTranslationProfile: StencilReactComponent<
	AppTranslationProfileElement,
	AppTranslationProfileEvents,
	Components.AppTranslationProfile
> = /*@__PURE__*/ createComponent<
	AppTranslationProfileElement,
	AppTranslationProfileEvents,
	Components.AppTranslationProfile
>({
	tagName: "app-translation-profile",
	elementClass: AppTranslationProfileElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTranslationProfileEvents,
	defineCustomElement: defineAppTranslationProfile,
});

export type AppTranslationShellEvents = NonNullable<unknown>;

export const AppTranslationShell: StencilReactComponent<
	AppTranslationShellElement,
	AppTranslationShellEvents,
	Components.AppTranslationShell
> = /*@__PURE__*/ createComponent<
	AppTranslationShellElement,
	AppTranslationShellEvents,
	Components.AppTranslationShell
>({
	tagName: "app-translation-shell",
	elementClass: AppTranslationShellElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTranslationShellEvents,
	defineCustomElement: defineAppTranslationShell,
});

export type AppTranslationsHostEvents = NonNullable<unknown>;

export const AppTranslationsHost: StencilReactComponent<
	AppTranslationsHostElement,
	AppTranslationsHostEvents,
	Components.AppTranslationsHost
> = /*@__PURE__*/ createComponent<
	AppTranslationsHostElement,
	AppTranslationsHostEvents,
	Components.AppTranslationsHost
>({
	tagName: "app-translations-host",
	elementClass: AppTranslationsHostElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTranslationsHostEvents,
	defineCustomElement: defineAppTranslationsHost,
});

export type AppTsQueryHoverPrefetchEvents = NonNullable<unknown>;

export const AppTsQueryHoverPrefetch: StencilReactComponent<
	AppTsQueryHoverPrefetchElement,
	AppTsQueryHoverPrefetchEvents,
	Components.AppTsQueryHoverPrefetch
> = /*@__PURE__*/ createComponent<
	AppTsQueryHoverPrefetchElement,
	AppTsQueryHoverPrefetchEvents,
	Components.AppTsQueryHoverPrefetch
>({
	tagName: "app-ts-query-hover-prefetch",
	elementClass: AppTsQueryHoverPrefetchElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryHoverPrefetchEvents,
	defineCustomElement: defineAppTsQueryHoverPrefetch,
});

export type AppTsQueryPostsEvents = NonNullable<unknown>;

export const AppTsQueryPosts: StencilReactComponent<
	AppTsQueryPostsElement,
	AppTsQueryPostsEvents,
	Components.AppTsQueryPosts
> = /*@__PURE__*/ createComponent<AppTsQueryPostsElement, AppTsQueryPostsEvents, Components.AppTsQueryPosts>({
	tagName: "app-ts-query-posts",
	elementClass: AppTsQueryPostsElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryPostsEvents,
	defineCustomElement: defineAppTsQueryPosts,
});

export type AppTsQueryPostsSignalsEvents = NonNullable<unknown>;

export const AppTsQueryPostsSignals: StencilReactComponent<
	AppTsQueryPostsSignalsElement,
	AppTsQueryPostsSignalsEvents,
	Components.AppTsQueryPostsSignals
> = /*@__PURE__*/ createComponent<
	AppTsQueryPostsSignalsElement,
	AppTsQueryPostsSignalsEvents,
	Components.AppTsQueryPostsSignals
>({
	tagName: "app-ts-query-posts-signals",
	elementClass: AppTsQueryPostsSignalsElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryPostsSignalsEvents,
	defineCustomElement: defineAppTsQueryPostsSignals,
});

export type AppTsQueryPrefetchEvents = NonNullable<unknown>;

export const AppTsQueryPrefetch: StencilReactComponent<
	AppTsQueryPrefetchElement,
	AppTsQueryPrefetchEvents,
	Components.AppTsQueryPrefetch
> = /*@__PURE__*/ createComponent<AppTsQueryPrefetchElement, AppTsQueryPrefetchEvents, Components.AppTsQueryPrefetch>({
	tagName: "app-ts-query-prefetch",
	elementClass: AppTsQueryPrefetchElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryPrefetchEvents,
	defineCustomElement: defineAppTsQueryPrefetch,
});

export type AppTsQueryPrefetchDemoEvents = NonNullable<unknown>;

export const AppTsQueryPrefetchDemo: StencilReactComponent<
	AppTsQueryPrefetchDemoElement,
	AppTsQueryPrefetchDemoEvents,
	Components.AppTsQueryPrefetchDemo
> = /*@__PURE__*/ createComponent<
	AppTsQueryPrefetchDemoElement,
	AppTsQueryPrefetchDemoEvents,
	Components.AppTsQueryPrefetchDemo
>({
	tagName: "app-ts-query-prefetch-demo",
	elementClass: AppTsQueryPrefetchDemoElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryPrefetchDemoEvents,
	defineCustomElement: defineAppTsQueryPrefetchDemo,
});

export type AppTsQueryPrefetchReuseEvents = NonNullable<unknown>;

export const AppTsQueryPrefetchReuse: StencilReactComponent<
	AppTsQueryPrefetchReuseElement,
	AppTsQueryPrefetchReuseEvents,
	Components.AppTsQueryPrefetchReuse
> = /*@__PURE__*/ createComponent<
	AppTsQueryPrefetchReuseElement,
	AppTsQueryPrefetchReuseEvents,
	Components.AppTsQueryPrefetchReuse
>({
	tagName: "app-ts-query-prefetch-reuse",
	elementClass: AppTsQueryPrefetchReuseElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryPrefetchReuseEvents,
	defineCustomElement: defineAppTsQueryPrefetchReuse,
});

export type AppTsQueryUseQueriesDemoEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesDemo: StencilReactComponent<
	AppTsQueryUseQueriesDemoElement,
	AppTsQueryUseQueriesDemoEvents,
	Components.AppTsQueryUseQueriesDemo
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesDemoElement,
	AppTsQueryUseQueriesDemoEvents,
	Components.AppTsQueryUseQueriesDemo
>({
	tagName: "app-ts-query-use-queries-demo",
	elementClass: AppTsQueryUseQueriesDemoElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryUseQueriesDemoEvents,
	defineCustomElement: defineAppTsQueryUseQueriesDemo,
});

export type AppTsQueryUseQueriesInlineEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesInline: StencilReactComponent<
	AppTsQueryUseQueriesInlineElement,
	AppTsQueryUseQueriesInlineEvents,
	Components.AppTsQueryUseQueriesInline
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesInlineElement,
	AppTsQueryUseQueriesInlineEvents,
	Components.AppTsQueryUseQueriesInline
>({
	tagName: "app-ts-query-use-queries-inline",
	elementClass: AppTsQueryUseQueriesInlineElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryUseQueriesInlineEvents,
	defineCustomElement: defineAppTsQueryUseQueriesInline,
});

export type AppTsQueryUseQueriesReuseEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesReuse: StencilReactComponent<
	AppTsQueryUseQueriesReuseElement,
	AppTsQueryUseQueriesReuseEvents,
	Components.AppTsQueryUseQueriesReuse
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesReuseElement,
	AppTsQueryUseQueriesReuseEvents,
	Components.AppTsQueryUseQueriesReuse
>({
	tagName: "app-ts-query-use-queries-reuse",
	elementClass: AppTsQueryUseQueriesReuseElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryUseQueriesReuseEvents,
	defineCustomElement: defineAppTsQueryUseQueriesReuse,
});

export type AppTsQueryUseQueriesSignalsEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesSignals: StencilReactComponent<
	AppTsQueryUseQueriesSignalsElement,
	AppTsQueryUseQueriesSignalsEvents,
	Components.AppTsQueryUseQueriesSignals
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesSignalsElement,
	AppTsQueryUseQueriesSignalsEvents,
	Components.AppTsQueryUseQueriesSignals
>({
	tagName: "app-ts-query-use-queries-signals",
	elementClass: AppTsQueryUseQueriesSignalsElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryUseQueriesSignalsEvents,
	defineCustomElement: defineAppTsQueryUseQueriesSignals,
});

export type AppTsQueryUseQueriesSignalsCombineEvents = NonNullable<unknown>;

export const AppTsQueryUseQueriesSignalsCombine: StencilReactComponent<
	AppTsQueryUseQueriesSignalsCombineElement,
	AppTsQueryUseQueriesSignalsCombineEvents,
	Components.AppTsQueryUseQueriesSignalsCombine
> = /*@__PURE__*/ createComponent<
	AppTsQueryUseQueriesSignalsCombineElement,
	AppTsQueryUseQueriesSignalsCombineEvents,
	Components.AppTsQueryUseQueriesSignalsCombine
>({
	tagName: "app-ts-query-use-queries-signals-combine",
	elementClass: AppTsQueryUseQueriesSignalsCombineElement,
	// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
	react: React,
	events: {} as AppTsQueryUseQueriesSignalsCombineEvents,
	defineCustomElement: defineAppTsQueryUseQueriesSignalsCombine,
});

export type SsvComposeEvents = { onComposeEvent: EventName<SsvComposeCustomEvent<ComposeEventDetail>> };

export const SsvCompose: StencilReactComponent<SsvComposeElement, SsvComposeEvents, Components.SsvCompose> =
	/*@__PURE__*/ createComponent<SsvComposeElement, SsvComposeEvents, Components.SsvCompose>({
		tagName: "ssv-compose",
		elementClass: SsvComposeElement,
		// @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
		react: React,
		events: { onComposeEvent: "composeEvent" } as SsvComposeEvents,
		defineCustomElement: defineSsvCompose,
	});
