packages:
  - "apps/*"
  - "libs/*"

catalog:
  # ── TypeScript & Build ────────────────────────────────────────────────────────
  typescript: ^6.0.3

  # ── Linting & Formatting ────────────────────────────────────────────────────────
  oxlint: 1.62.0
  oxfmt: ^0.49.0

  # ── StencilJS ─────────────────────────────────────────────────────────────────
  "@stencil/core": 4.43.4
  "@stencil/react-output-target": ^1.5.2
