/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestChild {
    }
    interface TestCounter {
    }
    interface TestCtxConsumer {
    }
    interface TestCtxProvider {
    }
    interface TestParent {
    }
}
declare global {
    interface HTMLTestChildElement extends Components.TestChild, HTMLStencilElement {
    }
    var HTMLTestChildElement: {
        prototype: HTMLTestChildElement;
        new (): HTMLTestChildElement;
    };
    interface HTMLTestCounterElement extends Components.TestCounter, HTMLStencilElement {
    }
    var HTMLTestCounterElement: {
        prototype: HTMLTestCounterElement;
        new (): HTMLTestCounterElement;
    };
    interface HTMLTestCtxConsumerElement extends Components.TestCtxConsumer, HTMLStencilElement {
    }
    var HTMLTestCtxConsumerElement: {
        prototype: HTMLTestCtxConsumerElement;
        new (): HTMLTestCtxConsumerElement;
    };
    interface HTMLTestCtxProviderElement extends Components.TestCtxProvider, HTMLStencilElement {
    }
    var HTMLTestCtxProviderElement: {
        prototype: HTMLTestCtxProviderElement;
        new (): HTMLTestCtxProviderElement;
    };
    interface HTMLTestParentElement extends Components.TestParent, HTMLStencilElement {
    }
    var HTMLTestParentElement: {
        prototype: HTMLTestParentElement;
        new (): HTMLTestParentElement;
    };
    interface HTMLElementTagNameMap {
        "test-child": HTMLTestChildElement;
        "test-counter": HTMLTestCounterElement;
        "test-ctx-consumer": HTMLTestCtxConsumerElement;
        "test-ctx-provider": HTMLTestCtxProviderElement;
        "test-parent": HTMLTestParentElement;
    }
}
declare namespace LocalJSX {
    interface TestChild {
    }
    interface TestCounter {
    }
    interface TestCtxConsumer {
    }
    interface TestCtxProvider {
    }
    interface TestParent {
    }
    interface IntrinsicElements {
        "test-child": TestChild;
        "test-counter": TestCounter;
        "test-ctx-consumer": TestCtxConsumer;
        "test-ctx-provider": TestCtxProvider;
        "test-parent": TestParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-child": LocalJSX.IntrinsicElements["test-child"] & JSXBase.HTMLAttributes<HTMLTestChildElement>;
            "test-counter": LocalJSX.IntrinsicElements["test-counter"] & JSXBase.HTMLAttributes<HTMLTestCounterElement>;
            "test-ctx-consumer": LocalJSX.IntrinsicElements["test-ctx-consumer"] & JSXBase.HTMLAttributes<HTMLTestCtxConsumerElement>;
            "test-ctx-provider": LocalJSX.IntrinsicElements["test-ctx-provider"] & JSXBase.HTMLAttributes<HTMLTestCtxProviderElement>;
            "test-parent": LocalJSX.IntrinsicElements["test-parent"] & JSXBase.HTMLAttributes<HTMLTestParentElement>;
        }
    }
}
