/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ComposeEventDetail } from "./compose/types";
export { ComposeEventDetail } from "./compose/types";
export namespace Components {
    interface SsvCompose {
        /**
          * Compose name string — looked up in the registry.
         */
        "name": string;
        /**
          * Props object passed to the resolved widget component.
          * @default undefined
         */
        "props": unknown;
    }
}
export interface SsvComposeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSsvComposeElement;
}
declare global {
    interface HTMLSsvComposeElementEventMap {
        "composeEvent": ComposeEventDetail;
    }
    interface HTMLSsvComposeElement extends Components.SsvCompose, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSsvComposeElementEventMap>(type: K, listener: (this: HTMLSsvComposeElement, ev: SsvComposeCustomEvent<HTMLSsvComposeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSsvComposeElementEventMap>(type: K, listener: (this: HTMLSsvComposeElement, ev: SsvComposeCustomEvent<HTMLSsvComposeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSsvComposeElement: {
        prototype: HTMLSsvComposeElement;
        new (): HTMLSsvComposeElement;
    };
    interface HTMLElementTagNameMap {
        "ssv-compose": HTMLSsvComposeElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface SsvCompose {
        /**
          * Compose name string — looked up in the registry.
         */
        "name": string;
        /**
          * Normalized output event from any wrapper component in this compose's subtree.
         */
        "onComposeEvent"?: (event: SsvComposeCustomEvent<ComposeEventDetail>) => void;
        /**
          * Props object passed to the resolved widget component.
          * @default undefined
         */
        "props"?: unknown;
    }

    interface SsvComposeAttributes {
        "name": string;
    }

    interface IntrinsicElements {
        "ssv-compose": Omit<SsvCompose, keyof SsvComposeAttributes> & { [K in keyof SsvCompose & keyof SsvComposeAttributes]?: SsvCompose[K] } & { [K in keyof SsvCompose & keyof SsvComposeAttributes as `attr:${K}`]?: SsvComposeAttributes[K] } & { [K in keyof SsvCompose & keyof SsvComposeAttributes as `prop:${K}`]?: SsvCompose[K] } & OneOf<"name", SsvCompose["name"], SsvComposeAttributes["name"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ssv-compose": LocalJSX.IntrinsicElements["ssv-compose"] & JSXBase.HTMLAttributes<HTMLSsvComposeElement>;
        }
    }
}
