import type { Champion } from "./lol.types";

const CDN = "https://ddragon.leagueoflegends.com/cdn/15.10.1/img/champion";

export const championsData: Champion[] = [
	{
		id: "aatrox",
		name: "Aatrox",
		roles: ["top"],
		difficulty: 4,
		iconUrl: `${CDN}/Aatrox.png`,
		tags: ["fighter"],
		lore: "A legendary warrior, the last of his kind, Aatrox wages endless battle.",
	},
	{
		id: "ahri",
		name: "Ahri",
		roles: ["mid"],
		difficulty: 5,
		iconUrl: `${CDN}/Ahri.png`,
		tags: ["mage", "assassin"],
		lore: "A vastaya with an innate connection to magic, Ahri can reshape life energy into orbs.",
	},
	{
		id: "caitlyn",
		name: "Caitlyn",
		roles: ["bot"],
		difficulty: 6,
		iconUrl: `${CDN}/Caitlyn.png`,
		tags: ["marksman"],
		lore: "Known for her grace and poise, Caitlyn is considered one of Piltover's finest officers.",
	},
	{
		id: "darius",
		name: "Darius",
		roles: ["top"],
		difficulty: 2,
		iconUrl: `${CDN}/Darius.png`,
		tags: ["fighter", "tank"],
		lore: "Noxus's greatest general, Darius has spent his life in service to his empire.",
	},
	{
		id: "ekko",
		name: "Ekko",
		roles: ["jungle", "mid"],
		difficulty: 8,
		iconUrl: `${CDN}/Ekko.png`,
		tags: ["assassin", "mage"],
		lore: "A prodigy from the rough streets of Zaun, Ekko can bend time to his will.",
	},
	{
		id: "fiora",
		name: "Fiora",
		roles: ["top"],
		difficulty: 9,
		iconUrl: `${CDN}/Fiora.png`,
		tags: ["fighter"],
		lore: "The most feared duelist in all Valoran, Fiora's blade is as sharp as her wit.",
	},
	{
		id: "graves",
		name: "Graves",
		roles: ["jungle"],
		difficulty: 5,
		iconUrl: `${CDN}/Graves.png`,
		tags: ["marksman"],
		lore: "An infamous outlaw and hired gun, Graves has walked the thin line between justice and crime.",
	},
	{
		id: "hecarim",
		name: "Hecarim",
		roles: ["jungle"],
		difficulty: 5,
		iconUrl: `${CDN}/Hecarim.png`,
		tags: ["fighter", "tank"],
		lore: "An ancient spirit of war, Hecarim's name is only spoken in the hushed tones of the fearing.",
	},
	{
		id: "jinx",
		name: "Jinx",
		roles: ["bot"],
		difficulty: 6,
		iconUrl: `${CDN}/Jinx.png`,
		tags: ["marksman"],
		lore: "A manic, mercurial criminal from Zaun, Jinx lives to spread chaos without care.",
	},
	{
		id: "katarina",
		name: "Katarina",
		roles: ["mid"],
		difficulty: 8,
		iconUrl: `${CDN}/Katarina.png`,
		tags: ["assassin", "mage"],
		lore: "Decisive in judgment and lethal in combat, Katarina is a Noxian assassin of the highest caliber.",
	},
	{
		id: "leesin",
		name: "Lee Sin",
		roles: ["jungle"],
		difficulty: 10,
		iconUrl: `${CDN}/LeeSin.png`,
		tags: ["fighter", "tank"],
		lore: "A master of the Ionian martial art of Wuju, Lee Sin is a turbulent spirit devoted to justice.",
	},
	{
		id: "lulu",
		name: "Lulu",
		roles: ["support"],
		difficulty: 5,
		iconUrl: `${CDN}/Lulu.png`,
		tags: ["support", "mage"],
		lore: "A yordle mage who spent years in the enchanted Glade, Lulu alters reality on a whim.",
	},
	{
		id: "malzahar",
		name: "Malzahar",
		roles: ["mid"],
		difficulty: 2,
		iconUrl: `${CDN}/Malzahar.png`,
		tags: ["mage"],
		lore: "A zealous prophet of the Void, Malzahar dedicates his powers to calling for its arrival.",
	},
	{
		id: "nautilus",
		name: "Nautilus",
		roles: ["support", "top"],
		difficulty: 4,
		iconUrl: `${CDN}/Nautilus.png`,
		tags: ["tank", "support"],
		lore: "A lonely wanderer of the deep, Nautilus drifts through the waters wearing an immense iron suit.",
	},
	{
		id: "orianna",
		name: "Orianna",
		roles: ["mid"],
		difficulty: 7,
		iconUrl: `${CDN}/Orianna.png`,
		tags: ["mage"],
		lore: "A young woman who became more machine than human after a tragic childhood accident.",
	},
	{
		id: "pyke",
		name: "Pyke",
		roles: ["support"],
		difficulty: 7,
		iconUrl: `${CDN}/Pyke.png`,
		tags: ["assassin", "support"],
		lore: "A drowned sailor brought back from death, Pyke hunts his killers one by one.",
	},
	{
		id: "qiyana",
		name: "Qiyana",
		roles: ["mid", "jungle"],
		difficulty: 9,
		iconUrl: `${CDN}/Qiyana.png`,
		tags: ["assassin"],
		lore: "Arrogant, temperamental, and gifted beyond all measure, Qiyana is Ixtal's greatest elementalist.",
	},
	{
		id: "renekton",
		name: "Renekton",
		roles: ["top"],
		difficulty: 4,
		iconUrl: `${CDN}/Renekton.png`,
		tags: ["fighter", "tank"],
		lore: "Renekton is a fearsome, primal warrior from the scorched deserts of Shurima.",
	},
	{
		id: "sejuani",
		name: "Sejuani",
		roles: ["jungle"],
		difficulty: 4,
		iconUrl: `${CDN}/Sejuani.png`,
		tags: ["tank", "fighter"],
		lore: "Sejuani is the brutal, unforgiving Warmother of the Winter's Claw, one of the most fearsome Freljordian tribes.",
	},
	{
		id: "thresh",
		name: "Thresh",
		roles: ["support"],
		difficulty: 7,
		iconUrl: `${CDN}/Thresh.png`,
		tags: ["support", "tank"],
		lore: "Sadistic and cunning, Thresh is a ghost who harvests the souls of the living for his own dark ends.",
	},
];
